---
- name: Install Wget
  yum: name=wget state=present

- name: Download JAVA JDK 8 
  get_url: 

    url: http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
    dest: /opt/jdk-8u181-linux-x64.tar.gz
    headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'

- name: JDK 8 Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/jdk-8u181-linux-x64.tar.gz -C /opt/ creates=/opt/jdk1.8.0_181

- name: JDK 8 Symlink install directory
  file: src=/opt/jdk1.8.0_181 path=/opt/java state=link

- name: JDK 8 correct java version selected
  alternatives:
    name: java
    link: /usr/bin/java
    path: /opt/java/bin/java

- name: JDK 8 correct jar version selected
  alternatives:
    name: jar
    link: /usr/bin/jar
    path: /opt/java/bin/jar

- name: JDK 8 correct javac version selected
  alternatives:
    name: javac
    link: /usr/bin/javac
    path: /opt/java/bin/javac
